version: '3.0'

services:
  mysql:
    image: mysql:8.0
    restart: on-failure
    environment:
      MYSQL_USER: epsi
      MYSQL_PASSWORD: epsimysql
      MYSQL_ROOT_PASSWORD: epsiroot
      MYSQL_DATABASE: epsi
    volumes:
      - ./sqlscripts/:/docker-entrypoint-initdb.d
    ports:
      - '${MYSQL_PORT}:3306'
    command: ["/wait-for-it.sh", "mysql:3306", "--", "echo", "mysql is ready"]

  php:
    build:
      context: .
      dockerfile: docker/php/DockerfileJenkins
    restart: on-failure
    volumes:
      - '.:/usr/src/app'
    user: ${LOCAL_USER}:${LOCAL_USER}

  nginx:
    image: nginx:1.19.0-alpine
    restart: on-failure
    depends_on:
      - php
    volumes:
      - './public/:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '${NGINX_PORT}:80'

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - '${ADMINER_PORT}:8080'