version: '3.0'

services:
  mysql:
   image: mysql:8.0
   restart: on-failure
   environment:
     MYSQL_USER: ${MYSQL_USER}
     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
     MYSQL_DATABASE: ${MYSQL_DATABASE}

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    volumes:
      - '.:/usr/src/app'
    user: ${LOCAL_USER}

  nginx:
    image: nginx:1.19.0-alpine
    restart: on-failure
    depends_on:
      - php
    volumes:
      - './public/:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '${NGINX_PORT}:80'

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - '${ADMINER_PORT}:8080'