pipeline {
    agent { label 'epsi' }
    stages {
        stage ('clone + install dnt4-test') {
            steps {
                sh '''
                    cp -f .env.tst .env
                    echo "DATABASE_URL=mysql://epsi:epsimysql@mysql:3306/epsi" > .env.local
                    rm docker/php/Dockerfile
                    mv docker/php/DockerfileJenkins docker/php/Dockerfile
                    docker-compose down
                    docker-compose up -d
                    docker-compose exec -T php composer install
                    docker-compose exec -T php sh -c "php bin/console doctrine:schema:update --force"
                '''
            }
        }
        stage ('Unit test + Integration test') {
            steps {
                sh '''
                    curl http://localhost:81/api
                '''
            }
        }
        stage ('Run SonarQube') {
            steps {
                sh '''
                    docker run -d -p 9000:9000 -p 9092:9092 --name sonarqube sonarqube:6.7-alpine
                    curl http://localhost:9092
                '''
            }
        }
    }  
}
