<?php


namespace App\Tests\Entity;

use App\Entity\DataFile;
use App\Entity\File;
use PHPUnit\Framework\TestCase;

class DataFileTest extends TestCase
{

    /**
     * @var DataFile
     */
    private $datafile;

    /**
     * @var File
     */
    private $file;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->datafile = new DataFile();
        $this->file = new File();
    }

    public function testGetName(){
        $value = "name";
        $response = $this->datafile->setName($value);
        self::assertInstanceOf(DataFile::class, $response);
        self::assertEquals($value, $this->datafile->getName());
    }

    public function testGetContent(){
        $value = "abcd";
        $response = $this->datafile->setContent($value);
        self::assertInstanceOf(DataFile::class, $response);
        self::assertEquals($value, $this->datafile->getContent());
    }

    public function testGetFile(){
        $value = $this->file->setName("nameFile");
        $response = $this->datafile->setFile($value);
        self::assertInstanceOf(DataFile::class, $response);
        self::assertEquals($value, $this->datafile->getFile());
    }
}