<?php


namespace App\Tests\Entity;


use App\Entity\DataFile;
use App\Entity\File;
use PHPUnit\Framework\TestCase;

class FileTest extends TestCase
{
    /**
     * @var File
     */
    private $file;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->file = new File();
    }

    public function testGetNameEntity(){
        $value = "nameFileTest";
        $response = $this->file->setName($value);
        self::assertInstanceOf(File::class, $response);
        self::assertEquals($value, $this->file->getName());
    }

    public function testGetDataFileEntity(){
        $response = $this->file->addData(new DataFile());
        self::assertInstanceOf(File::class, $response);
        self::assertCount(1, $this->file->getData());
    }
}